#!/bin/sh

echo -n -e "HTTP/1.0 200 OK\r\n"
echo -n -e "Content-type: text/plain\r\n"
echo -n -e "\r\n"

echo -n -e "query string: $QUERY_STRING\n\n"

qs=( $QUERY_STRING )
pertama=${qs[0]}
kedua=${qs[1]}
jumlah=$(( $pertama + $kedua ))

echo -n -e "bilangan pertama: $pertama\n";
echo -n -e "bilangan kedua  : $kedua\n";
echo -n -e "jumlah          : $jumlah\n";

